### ISSUE TITLE
Model Does not Converge

### ISSUE THREAD

**Issue by vijaysumaravi** [adbailey1/DepAudioNet_reproduction#2]
Hi Andrew,

Thank you for this repository. I am trying to reproduce the results from the DepAudioNet paper but my model does not converge. I am using the provided conda environment. 

Sorry in advance for the long post. 

My feature creation config is like this: 

```
EXPERIMENT_DETAILS = {'FEATURE_EXP': 'mel',
                      'FREQ_BINS': 40,
                      'DATASET_IS_BACKGROUND': False,
                      'WHOLE_TRAIN': False,
                      'WINDOW_SIZE': 1024,
                      'OVERLAP': 50,
                      'SVN': True,
                      'SAMPLE_RATE': 16000,
                      'REMOVE_BACKGROUND': True}
# Set True to split data into genders
GENDER = False
```
My feature folder that gets created is 'mel_svn_exp'. 

My experiment config is like this:

```
EXPERIMENT_DETAILS = {'FEATURE_EXP': 'mel',
                      'CLASS_WEIGHTS': False,
                      'USE_GENDER_WEIGHTS': False,
                      'SUB_SAMPLE_ND_CLASS': True,  # Make len(dep) == len(
                      # ndep)
                      'CROP': True,
                      'OVERSAMPLE': False,
                      'SPLIT_BY_GENDER': True,  # Only for use in test mode
                      'FEATURE_DIMENSIONS': 120,
                      'FREQ_BINS': 40,
                      'BATCH_SIZE': 20,
                      'SVN': True,
                      'LEARNING_RATE': 1e-3,
                      'SEED': 1000,
                      'TOTAL_EPOCHS': 100,
                      'TOTAL_ITERATIONS': 3280,
                      'ITERATION_EPOCH': 1,
                      'SUB_DIR': 'exp_1',
                      'EXP_RUNTHROUGH': 5}
# Determine the level of crop, min file found in training set or maximum file
# per set (ND / D) or (FND, MND, FD, MD)
MIN_CROP = True
# Determine whether the experiment is run in terms of 'epoch' or 'iteration'
ANALYSIS_MODE = 'epoch'

# How to calculate the weights: 'macro' uses the number of individual
# interviews, 'micro' uses the number of instances of both classes, 'both'
# combines the macro and micro via the product, 'instance' uses the total
# number of segments for each class to determine the weights.
WEIGHT_TYPE = 'instance'

# Set to 'm' or 'f' to split into male or female respectively
# Otherwise set to '-' to keep both genders in the database
GENDER = '-'

# These values should be the same as those used to create the database
# If raw audio is used, you might want to set these to the conv kernel and
# stride values
WINDOW_SIZE = 1024
HOP_SIZE = 512
OVERLAP = int((HOP_SIZE / WINDOW_SIZE) * 100)
```

The model does not converge. My dev loss does not reduce and the training ends with this message:

```
 ###############################################################
train accuracy at epoch: 100
train Accuracy: Mean: 0.926 - [0.913 0.939], F1_Score: Mean: 0.926 - [0.924 0.927], Loss: 0.154
############################################################### 


 ###############################################################
dev accuracy at epoch: 100
dev Accuracy: Mean: 0.473 - [0.614 0.333], F1_Score: Mean: 0.463 - [0.684 0.242], Loss: 0.756
############################################################### 

Reducing Learning rate from:  5.7264168970223554e-06  to  5.15377520732012e-06
Saving the Model at epoch:  100
System will exit as the validation loss has not improved for {patience} epochs
[0.8878887778887774, 0.8590675990675987, 0.9167099567099564, 0.886863145358262, 0.8823694713900954, 0.8913568193264287, 0.22399778601093528, 0.5696969696969697, 0.6727272727272726, 0.4666666666666667, 0.5413045789079798, 0.7388441521154699, 0.3437650057004896, 0.8136677861213684]

```

As a sanity check, based on your reply for another issue, I tried printing the first value of the mel_svn_feature. My output is "-0.07406965". This is for the folder '300'. Not sure why this value is different from yours. 

Other changes I've made:

I had to slightly modify the data_loader code to make it work for the latest version of the daic-woz dataset that I downloaded: 

1) The dataset did not have separate transcripts for participant and prompter. So I just take the start and end times from the Transcript files. (the function transcript_file_processing() int utils/utilities.py file.) I copied the changed function [here](https://pastebin.com/8BcdcpwV). 
2) My Transcripts were already clean - no background words like [laugh], [breath], etc.  
2) The order of the labels was different. My labels were: Folder_name, Gender, PHQ8_Binary, PHQ8_score. I had to change the label's index( line 1089 in data_loader/organiser.py). 

I'm not sure if my changes are causing the issue. Please let me know if I am missing something. Any suggestions will be helpful. Thanks again!

**Comment by adbailey1** [comment]
Hi vijaysumaravi, 

Thanks for this. 

Ok I'll start with your comments at the bottom: 

1) - There were not separate files for the participant/prompter for me either, but in my version of the dataset, every folder has a transcript.csv file where each line depicts either the participant or the prompter's speech. Each line starts with onset/offset times followed by the speaker ID (participant or prompter) followed by the transcript. Check the format of your data's transcript.csv file and change your code to add back in whatever is written as the speaker ID for the participant. Like I said, for me it was "participant" or "Participant". This may explain the difference in the result of the mel_svn_feature you received: "-0.07406965" compared with my: "-0.023413863". If this is true it will then have a knock on effect to your final results. The section of code is used to capture the sections of speech spoken by the participant in order to cut out all the promoter's speech. There were a couple of files that did not follow this format for the transcript files but I added an exception for these. 

2) Again just do a sanity check on this and load up a couple of transcript.csv files and search for "laugh" or "sigh". I found instances of both in files 492 and 490. If they have cleaned the data and removed this then that's great but actually it shouldn't affect the functionality of the code as it just passes this check through an IF statement. Further to this, we are only concerned about the actual textual output if we are performing some sort of text analysis, so for this case where we only care about the audio, these won't be checked. Also to note that the file config_odd_words.py is there for information only in this instance as it is used for text analysis.  

3) Ok, interesting that they changed the labels, so yes I had it in the form Folder, PHQ8_Binary, PHQ8_Score, Gender so as long as your code ends up in that format it should be fine. 

Now to the main problem, what should happen once you train your model is the experiment will run 5 times and save the output to 5 different directories. In the last experiment, if you go to mel_svn_exp/exp_1/log/model_5.log at the bottom of that file you should see a long list of outputs called "scores". 

If you take the very last list inside the [...] that should be the averaged best epoch scores for the experiment. I find it helpful to put this into an excel sheet and split the numbers into columns via the separating commas. The headings will be Train_Acc_Avg, Train_Acc_NonDep, Train_Acc_Dep, Train_F1_avg, Train_F1_NonDep, Train_F1_Dep, Loss, Val_Acc_Avg, Val_Acc_NonDep, Val_Acc_Dep, Val_F1_avg, Val_F1_NonDep, Val_F1_Dep, Loss. 

If you can check to see if you are getting these outputs in the log files that should help. Results will vary from computer to computer and different versions of Python/Pytorch etc. will also affect the results. But I would also re-process the data according to the comment, 1),  above. If this doesn't help, get back to me and we will try something else.

Otherwise your settings look fine. I am looking to upload a newer version of the code which will be neater and more readable.

Thanks again, 

Andrew

**Comment by vijaysumaravi** [comment]
Hi Andrew,

Thanks for the quick reply. 

My transcript files are in this format:
Start_Time,End_Time,Text,Confidence

I am assuming they have cleaned up the transcripts to include only the participant's text. I checked both 492_P and 490_P transcripts and couldn't find 'laugh' or 'sigh' in either of them. 

Here's the last line from mel_svn_exp/exp_1/log/model_*.log:



Log | Train_Acc_Avg | Train_Acc_NonDep | Train_Acc_Dep | Train_F1_avg | Train_F1_NonDep | Train_F1_Dep | Loss | Val_Acc_Avg | Val_Acc_NonDep | Val_Acc_Dep | Val_F1_avg | Val_F1_NonDep | Val_F1_Dep | Loss
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Model 1 | 0.874675325 | 0.819480519 | 0.929870130 | 0.873377952 | 0.864422939 | 0.882332964 | 0.239588106 | 0.549242424 | 0.681818182 | 0.416666667 | 0.531660693 | 0.740740741 | 0.322580645 | 0.84773159
Model 2 | 0.876623377 | 0.863636364 | 0.889610390 | 0.875699494 | 0.874073501 | 0.877325488 | 0.247649725 | 0.602272727 | 0.704545455 | 0.500000000 | 0.576264436 | 0.765432099 | 0.387096774 | 0.772097707
Model 3 | 0.875324675 | 0.853246753 | 0.897402597 | 0.874343150 | 0.871030993 | 0.877655306 | 0.260460916 | 0.609848485 | 0.636363636 | 0.583333333 | 0.563636364 | 0.727272727 | 0.400000000 | 0.868959904
Model 4 | 0.906410256 | 0.874358974 | 0.938461538 | 0.905564793 | 0.901588354 | 0.909541232 | 0.191031248 | 0.500000000 | 0.750000000 | 0.250000000 | 0.499105546 | 0.76744186 | 0.230769231 | 0.789151073
Model 5 | 0.887888778 | 0.859067599 | 0.916709957 | 0.886863145 | 0.882369471 | 0.891356819 | 0.223997786 | 0.56969697 | 0.672727273 | 0.466666667 | 0.541304579 | 0.738844152 | 0.343765006 | 0.813667786


My val_f1_avg is around 0.53-0.57. Could the difference in reported results and my results be because of the changes in data clean up? 

Best,
Vijay

**Comment by vijaysumaravi** [comment]
Also, I was reading your paper - RAW AUDIO FOR DEPRESSION DETECTION CAN BE MORE ROBUST AGAINST GENDER IMBALANCE THAN MEL-SPECTROGRAM FEATURES. 

You mention that your dataset is 107 files for training, 35 for validation and 47 for test. Is that the dataset you used to reproduce the DepAudioNet results? 

The DAIC-WOZ dataset I have has 163 train files, 56 validation files and 56 test files. My folders are from 300-718 (although the official documentation says data is 300-492).

**Comment by vijaysumaravi** [comment]
The dataset I have is the extended DIAC-WOZ dataset. I'm closing the issue. I will run the experiments on the original dataset and check my results. Thanks for the help!
